

version: '3.6'

services:

  mysql:
    image: mysql
    platform: linux/amd64
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: brumar

    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - app_db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    networks:
      - nt_mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  app_db:

networks:
  nt_mysql:
    driver: bridge